/**
 * Neural-Janitor — Constants & Category Definitions
 *
 * Each category has:
 *   - keywords: URL substrings / hostname fragments used for fast matching
 *   - maxAgeMs: how long a tab in this category may stay open WITHOUT any visit
 *   - priority:  lower = cleaned sooner (used when ML idle-window is available)
 *
 * NSFW gets the shortest window — even 12 h is generous for a tab you opened
 * once and walked away from. AI tools get the longest default window because
 * long-running research/chat sessions are often intentionally kept around.
 */

export const APP_NAME = 'Neural-Janitor';
export const ENGINE_CODENAME = 'The Chronos Engine';
export const IPC_PROTOCOL_VERSION = 2;

export const HARDWARE_MARKER_STATES = Object.freeze({
  AUTO: 'auto',             // Core ML Auto can use this device.
  ACTIVE: 'active',         // Known active fallback path.
  STANDBY: 'standby',       // Available/known, but not current path.
  UNAVAILABLE: 'unavailable',
  ERROR: 'error',           // Telemetry link is offline or inconsistent.
});

export const CATEGORIES = {
  nsfw: {
    label: 'NSFW',
    keywords: [
      'porn', 'xvideos', 'xnxx', 'xhamster', 'pornhub', 'redtube',
      'brazzers', 'onlyfans', 'chaturbate', 'stripchat',
      'hentai', 'nhentai', 'gelbooru', 'danbooru',
      'rule34', 'e-hentai', 'exhentai',
    ],
    maxAgeMs: 12 * 60 * 60 * 1000,       // 12 hours
    priority: 0,
    color: '#e74c3c',
  },
  finance: {
    label: 'Finance & Banking',
    keywords: [
      'bank', 'chase', 'wellsfargo', 'citibank', 'hsbc',
      'paypal', 'stripe', 'venmo', 'cashapp', 'robinhood',
      'fidelity', 'schwab', 'vanguard', 'etrade', 'coinbase',
      'binance', 'kraken', 'crypto', 'defi', 'webull',
      'etrade', 'tdameritrade', 'ally.com', 'sofi.com',
      'mint.com', 'creditkarma', 'bankofamerica',
      'mufg.jp', 'smbc.co.jp', 'mizuhobank.co.jp', 'rakuten-sec.co.jp',
      'sbisec.co.jp', 'monex.co.jp', 'jpx.co.jp',
      'alipay.com', 'tenpay.com', 'eastmoney.com', 'xueqiu.com',
      'futunn.com', 'tigerbrokers', 'joinquant.com', 'finviz.com',
    ],
    maxAgeMs: 14 * 24 * 60 * 60 * 1000,  // 14 days
    priority: 80,
    color: '#27ae60',
  },
  ai: {
    label: 'AI Tools',
    keywords: [
      'chatgpt.com', 'chat.openai.com', 'openai.com',
      'deepseek.com', 'chat.deepseek.com',
      'claude.ai', 'anthropic.com',
      'gemini.google.com', 'bard.google.com',
      'aistudio.google.com', 'notebooklm.google.com',
      'huggingface.co', 'hf.co',
      'perplexity.ai', 'poe.com',
      'copilot.microsoft.com', 'mistral.ai',
      'chat.mistral.ai', 'qwen.ai', 'chat.qwen.ai',
      'kimi.moonshot.cn', 'doubao.com',
      'yuanbao.tencent.com', 'chatglm.cn',
      'yiyan.baidu.com', 'wenxin.baidu.com', 'tongyi.aliyun.com',
      'zhipuai.cn', 'bigmodel.cn', 'baichuan-ai.com',
      'minimax.chat', 'coze.cn', 'coze.com', 'dify.ai',
      'grok.com', 'x.ai',
      'phind.com', 'you.com', 'blackbox.ai',
      'openrouter.ai', 'lmarena.ai', 'replicate.com',
      'cursor.com', 'windsurf.com', 'v0.dev',
      'bolt.new', 'lovable.dev', 'replit.com',
    ],
    maxAgeMs: 30 * 24 * 60 * 60 * 1000,  // 30 days
    priority: 90,
    color: '#00c2ff',
  },
  email: {
    label: 'Email & Communication',
    keywords: [
      'mail.google', 'outlook.live', 'mail.yahoo', 'protonmail',
      'fastmail', 'zoho.com/mail', 'tutanota',
      'slack.com', 'teams.microsoft', 'discord.com',
      'telegram.org', 'web.whatsapp', 'signal.org',
      'mail.qq.com', 'mail.163.com', 'mail.126.com',
      'mail.sina.com.cn', 'mail.aliyun.com', 'mail.yahoo.co.jp',
      'chatwork.com', 'line.me', 'worksmobile.com',
    ],
    maxAgeMs: 14 * 24 * 60 * 60 * 1000,  // 14 days
    priority: 70,
    color: '#3498db',
  },
  work: {
    label: 'Work & Productivity',
    keywords: [
      'notion.so', 'confluence', 'jira', 'asana', 'trello',
      'monday.com', 'linear.app', 'figma.com', 'miro.com',
      'docs.google', 'sheets.google', 'slides.google',
      'office.com', 'onedrive', 'sharepoint',
      'github.com', 'gitlab.com', 'bitbucket',
      'vercel', 'netlify', 'aws.amazon', 'console.cloud',
      'heroku', 'digitalocean', 'linode',
      'qiita.com', 'zenn.dev', 'notion.site', 'cybozu.com',
      'backlog.com', 'esa.io', 'kintone.com', 'yuque.com',
      'teambition.com', 'feishu.cn', 'larksuite.com', 'coding.net',
      'gitee.com', 'tapd.cn', 'shimo.im',
    ],
    maxAgeMs: 14 * 24 * 60 * 60 * 1000,  // 14 days
    priority: 60,
    color: '#8e44ad',
  },
  social: {
    label: 'Social Media',
    keywords: [
      'facebook.com', 'twitter.com', 'x.com', 'instagram.com',
      'tiktok.com', 'reddit.com', 'linkedin.com', 'pinterest.com',
      'tumblr.com', 'mastodon', 'threads.net', 'weibo',
      'snapchat.com', 'vine.co',
      'weibo.com', 'xiaohongshu.com', 'zhihu.com',
      'douban.com', 'tieba.baidu.com', '5ch.net', '2ch.sc',
      'mixi.jp',
    ],
    maxAgeMs: 3 * 24 * 60 * 60 * 1000,   // 3 days
    priority: 20,
    color: '#e67e22',
  },
  news: {
    label: 'News & Media',
    keywords: [
      'cnn.com', 'bbc.com', 'nytimes.com', 'washingtonpost.com',
      'reuters.com', 'apnews.com', 'theguardian.com', 'bloomberg.com',
      'techcrunch.com', 'theverge.com', 'arstechnica.com',
      'wired.com', 'hacker-news', 'news.ycombinator',
      'nhk.or.jp', 'asahi.com', 'yomiuri.co.jp', 'mainichi.jp',
      'sankei.com', 'nikkei.com', 'news.yahoo.co.jp',
      'itmedia.co.jp', 'gigazine.net', 'toyokeizai.net',
      'diamond.jp', 'news.livedoor.com',
      '36kr.com', 'thepaper.cn', 'caixin.com', 'jiemian.com',
      'news.qq.com', 'news.sina.com.cn', 'toutiao.com', 'ifeng.com',
      'ithome.com', 'guancha.cn', 'people.com.cn', 'xinhuanet.com',
    ],
    maxAgeMs: 5 * 24 * 60 * 60 * 1000,   // 5 days
    priority: 30,
    color: '#f39c12',
  },
  shopping: {
    label: 'Shopping',
    keywords: [
      'amazon.com', 'ebay.com', 'aliexpress', 'etsy.com',
      'walmart.com', 'target.com', 'bestbuy.com',
      'shopify', 'newegg.com', 'costco.com',
      'taobao.com', 'tmall.com', 'jd.com', 'pinduoduo.com',
      'rakuten.co.jp', 'mercari.com', 'mercari.jp',
      'yodobashi.com', 'zozo.jp', 'yahoo.co.jp/shopping',
      'kakaku.com',
    ],
    maxAgeMs: 7 * 24 * 60 * 60 * 1000,   // 7 days
    priority: 40,
    color: '#1abc9c',
  },
  entertainment: {
    label: 'Entertainment',
    keywords: [
      'youtube.com', 'netflix.com', 'twitch.tv', 'spotify.com',
      'hbomax.com', 'disneyplus.com', 'hulu.com', 'peacocktv',
      'crunchyroll.com', 'vimeo.com', 'dailymotion',
      'imdb.com', 'rottentomatoes',
      'bilibili.com', 'nicovideo.jp', 'niconico', 'abema.tv',
      'tver.jp', 'pixiv.net', 'douyin.com', 'kuaishou.com',
      'youku.com', 'iqiyi.com', 'acfun.cn', 'music.163.com',
    ],
    maxAgeMs: 5 * 24 * 60 * 60 * 1000,   // 5 days
    priority: 25,
    color: '#9b59b6',
  },
  reference: {
    label: 'Reference & Learning',
    keywords: [
      'wikipedia.org', 'stackoverflow.com', 'stackexchange',
      'medium.com', 'dev.to', 'mdn.', 'developer.mozilla',
      'coursera.org', 'udemy.com', 'edx.org', 'khanacademy',
      'duolingo.com', 'brilliant.org',
      'baike.baidu.com', 'zh.wikipedia.org',
      'ja.wikipedia.org', 'csdn.net', 'cnblogs.com', 'juejin.cn',
      'segmentfault.com', 'oschina.net', 'teratail.com',
      'note.com', 'hatena.ne.jp', 'kotobank.jp', 'weblio.jp',
      'developer.aliyun.com', 'cloud.tencent.com', 'infoq.cn',
      'sspai.com', 'zhihu.com', 'weread.qq.com', 'deepl.com',
      'lingq.com', 'tutorialsdojo.com', 'eikaiwa', 'skillbuilder',
      'learn.microsoft', 'developer.microsoft', 'azure.microsoft',
    ],
    maxAgeMs: 10 * 24 * 60 * 60 * 1000,  // 10 days
    priority: 50,
    color: '#2c3e50',
  },
};

// Fallback for URLs that don't match any category
export const DEFAULT_CATEGORY = {
  key: 'other',
  label: 'Other',
  maxAgeMs: 7 * 24 * 60 * 60 * 1000,    // 7 days
  priority: 50,
  color: '#95a5a6',
};

// ── Domain-to-Category Map (highest priority) ────────────────────────
// Maps hostname suffixes directly to category keys.  Checked BEFORE the
// per-category keyword lists so that known sites are never misclassified
// by generic keyword collisions (e.g. "open" in a Reuters URL).
//
// Keys are lowercase hostname fragments.  A hostname matches if it
// *ends with* the key (after stripping "www."), so "rakuten.co.jp"
// matches both "www.rakuten.co.jp" and "books.rakuten.co.jp".

export const DOMAIN_MAP = Object.freeze({
  // ── Finance ──
  'rakuten-card.co.jp': 'finance',
  'rakuten-card.jp': 'finance',
  'card.rakuten.co.jp': 'finance',
  'rakuten-bank.co.jp': 'finance',
  'rakuten-sec.co.jp': 'finance',
  'smbc-card.com': 'finance',
  'smbc.co.jp': 'finance',
  'mizuhobank.co.jp': 'finance',
  'mufg.jp': 'finance',
  'japanpost.jp': 'finance',
  'sbisec.co.jp': 'finance',
  'monex.co.jp': 'finance',
  'kabutan.jp': 'finance',
  'minkabu.jp': 'finance',
  'finance.yahoo.co.jp': 'finance',
  'finance.yahoo.com': 'finance',
  'stockscreener.yahoo.com': 'finance',
  'alipay.com': 'finance',
  'tenpay.com': 'finance',
  'eastmoney.com': 'finance',
  'xueqiu.com': 'finance',
  'futunn.com': 'finance',
  'tigerbrokers': 'finance',
  'joinquant.com': 'finance',
  'licai.com': 'finance',
  'chase.com': 'finance',
  'wellsfargo.com': 'finance',
  'citibank': 'finance',
  'hsbc': 'finance',
  'paypal.com': 'finance',
  'stripe.com': 'finance',
  'venmo.com': 'finance',
  'cashapp.com': 'finance',
  'robinhood.com': 'finance',
  'fidelity.com': 'finance',
  'schwab.com': 'finance',
  'vanguard.com': 'finance',
  'etrade.com': 'finance',
  'coinbase.com': 'finance',
  'binance.com': 'finance',
  'kraken.com': 'finance',
  'webull.com': 'finance',
  'tdameritrade.com': 'finance',
  'ally.com': 'finance',
  'sofi.com': 'finance',
  'mint.com': 'finance',
  'creditkarma.com': 'finance',
  'bankofamerica.com': 'finance',
  'investing.com': 'finance',
  'marketwatch.com': 'finance',
  'bloomberg.com': 'finance',
  'wsj.com': 'finance',
  'seekingalpha.com': 'finance',
  'morningstar.com': 'finance',
  'fool.com': 'finance',
  'macrotrends.net': 'finance',
  'finviz.com': 'finance',
  'tradingview.com': 'finance',
  'finviz': 'finance',

  // ── AI Tools ──
  'chatgpt.com': 'ai',
  'chat.openai.com': 'ai',
  'openai.com': 'ai',
  'deepseek.com': 'ai',
  'claude.ai': 'ai',
  'anthropic.com': 'ai',
  'gemini.google.com': 'ai',
  'aistudio.google.com': 'ai',
  'notebooklm.google.com': 'ai',
  'huggingface.co': 'ai',
  'perplexity.ai': 'ai',
  'poe.com': 'ai',
  'copilot.microsoft.com': 'ai',
  'mistral.ai': 'ai',
  'qwen.ai': 'ai',
  'chat.qwen.ai': 'ai',
  'kimi.moonshot.cn': 'ai',
  'doubao.com': 'ai',
  'yuanbao.tencent.com': 'ai',
  'chatglm.cn': 'ai',
  'yiyan.baidu.com': 'ai',
  'wenxin.baidu.com': 'ai',
  'tongyi.aliyun.com': 'ai',
  'zhipuai.cn': 'ai',
  'bigmodel.cn': 'ai',
  'baichuan-ai.com': 'ai',
  'minimax.chat': 'ai',
  'coze.cn': 'ai',
  'coze.com': 'ai',
  'dify.ai': 'ai',
  'grok.com': 'ai',
  'x.ai': 'ai',
  'phind.com': 'ai',
  'you.com': 'ai',
  'blackbox.ai': 'ai',
  'openrouter.ai': 'ai',
  'lmarena.ai': 'ai',
  'replicate.com': 'ai',
  'cursor.com': 'ai',
  'windsurf.com': 'ai',
  'v0.dev': 'ai',
  'bolt.new': 'ai',
  'lovable.dev': 'ai',
  'replit.com': 'ai',

  // ── Email & Communication ──
  'mail.google.com': 'email',
  'outlook.live.com': 'email',
  'mail.yahoo.com': 'email',
  'protonmail.com': 'email',
  'fastmail.com': 'email',
  'slack.com': 'email',
  'teams.microsoft.com': 'email',
  'discord.com': 'email',
  'telegram.org': 'email',
  'web.whatsapp.com': 'email',
  'signal.org': 'email',
  'mail.qq.com': 'email',
  'mail.163.com': 'email',
  'mail.126.com': 'email',
  'mail.sina.com.cn': 'email',
  'mail.aliyun.com': 'email',
  'mail.yahoo.co.jp': 'email',
  'chatwork.com': 'email',
  'line.me': 'email',
  'worksmobile.com': 'email',

  // ── Work & Productivity / Cloud ──
  'github.com': 'work',
  'gitlab.com': 'work',
  'bitbucket.org': 'work',
  'notion.so': 'work',
  'confluence': 'work',
  'jira': 'work',
  'asana.com': 'work',
  'trello.com': 'work',
  'monday.com': 'work',
  'linear.app': 'work',
  'figma.com': 'work',
  'miro.com': 'work',
  'docs.google.com': 'work',
  'sheets.google.com': 'work',
  'slides.google.com': 'work',
  'office.com': 'work',
  'onedrive.live.com': 'work',
  'sharepoint.com': 'work',
  'vercel.com': 'work',
  'netlify.com': 'work',
  'aws.amazon.com': 'work',
  'console.aws.amazon.com': 'work',
  'console.cloud.google.com': 'work',
  'cloud.google.com': 'work',
  'portal.azure.com': 'work',
  'azure.microsoft.com': 'work',
  'cloud.oracle.com': 'work',
  'oracle.com': 'work',
  'oracle.com/cloud': 'work',
  'console.oraclecloud.com': 'work',
  'xiaomi.com': 'work',
  'open.mimo.xiaomi.com': 'work',
  'microsoft.com': 'work',
  'office.com': 'work',
  'heroku.com': 'work',
  'digitalocean.com': 'work',
  'linode.com': 'work',
  'akamai.com': 'work',
  'vultr.com': 'work',
  'fly.io': 'work',
  'render.com': 'work',
  'railway.app': 'work',
  'qiita.com': 'work',
  'zenn.dev': 'work',
  'cybozu.com': 'work',
  'backlog.com': 'work',
  'esa.io': 'work',
  'kintone.com': 'work',
  'yuque.com': 'work',
  'teambition.com': 'work',
  'feishu.cn': 'work',
  'larksuite.com': 'work',
  'coding.net': 'work',
  'gitee.com': 'work',
  'tapd.cn': 'work',
  'shimo.im': 'work',
  'overleaf.com': 'work',

  // ── Social Media ──
  'facebook.com': 'social',
  'twitter.com': 'social',
  'x.com': 'social',
  'instagram.com': 'social',
  'tiktok.com': 'social',
  'reddit.com': 'social',
  'linkedin.com': 'social',
  'pinterest.com': 'social',
  'tumblr.com': 'social',
  'threads.net': 'social',
  'snapchat.com': 'social',
  'weibo.com': 'social',
  'xiaohongshu.com': 'social',
  'douban.com': 'social',
  'tieba.baidu.com': 'social',
  '5ch.net': 'social',
  '2ch.sc': 'social',
  'mixi.jp': 'social',
  'zhihu.com': 'reference',

  // ── News & Media ──
  'reuters.com': 'news',
  'cnn.com': 'news',
  'bbc.com': 'news',
  'nytimes.com': 'news',
  'washingtonpost.com': 'news',
  'apnews.com': 'news',
  'theguardian.com': 'news',
  'techcrunch.com': 'news',
  'theverge.com': 'news',
  'arstechnica.com': 'news',
  'wired.com': 'news',
  'news.ycombinator.com': 'news',
  'nhk.or.jp': 'news',
  'asahi.com': 'news',
  'yomiuri.co.jp': 'news',
  'mainichi.jp': 'news',
  'sankei.com': 'news',
  'nikkei.com': 'news',
  'news.yahoo.co.jp': 'news',
  'itmedia.co.jp': 'news',
  'gigazine.net': 'news',
  'toyokeizai.net': 'news',
  'diamond.jp': 'news',
  '36kr.com': 'news',
  'thepaper.cn': 'news',
  'caixin.com': 'news',
  'jiemian.com': 'news',
  'news.qq.com': 'news',
  'news.sina.com.cn': 'news',
  'toutiao.com': 'news',
  'ifeng.com': 'news',
  'ithome.com': 'news',
  'guancha.cn': 'news',
  'people.com.cn': 'news',
  'xinhuanet.com': 'news',

  // ── Shopping ──
  'amazon': 'shopping',
  'ebay.com': 'shopping',
  'aliexpress': 'shopping',
  'etsy.com': 'shopping',
  'walmart.com': 'shopping',
  'target.com': 'shopping',
  'bestbuy.com': 'shopping',
  'newegg.com': 'shopping',
  'costco.com': 'shopping',
  'taobao.com': 'shopping',
  'tmall.com': 'shopping',
  'jd.com': 'shopping',
  'pinduoduo.com': 'shopping',
  'rakuten.co.jp': 'shopping',
  'mercari.com': 'shopping',
  'mercari.jp': 'shopping',
  'yodobashi.com': 'shopping',
  'zozo.jp': 'shopping',
  'shopping.yahoo.co.jp': 'shopping',
  'kakaku.com': 'shopping',

  // ── Entertainment ──
  'youtube.com': 'entertainment',
  'netflix.com': 'entertainment',
  'twitch.tv': 'entertainment',
  'spotify.com': 'entertainment',
  'hbomax.com': 'entertainment',
  'disneyplus.com': 'entertainment',
  'hulu.com': 'entertainment',
  'crunchyroll.com': 'entertainment',
  'vimeo.com': 'entertainment',
  'imdb.com': 'entertainment',
  'bilibili.com': 'entertainment',
  'nicovideo.jp': 'entertainment',
  'abema.tv': 'entertainment',
  'tver.jp': 'entertainment',
  'pixiv.net': 'entertainment',
  'douyin.com': 'entertainment',
  'kuaishou.com': 'entertainment',
  'youku.com': 'entertainment',
  'iqiyi.com': 'entertainment',
  'acfun.cn': 'entertainment',
  'music.163.com': 'entertainment',

  // ── Reference & Learning ──
  'wikipedia.org': 'reference',
  'stackoverflow.com': 'reference',
  'stackexchange.com': 'reference',
  'medium.com': 'reference',
  'dev.to': 'reference',
  'developer.mozilla.org': 'reference',
  'coursera.org': 'reference',
  'udemy.com': 'reference',
  'edx.org': 'reference',
  'khanacademy.org': 'reference',
  'duolingo.com': 'reference',
  'brilliant.org': 'reference',
  'dictionary.cambridge.org': 'reference',
  'merriam-webster.com': 'reference',
  'dictionary.com': 'reference',
  'jisho.org': 'reference',
  'takoboto.jp': 'reference',
  'weblio.jp': 'reference',
  'kotobank.jp': 'reference',
  'baike.baidu.com': 'reference',
  'zh.wikipedia.org': 'reference',
  'ja.wikipedia.org': 'reference',
  'csdn.net': 'reference',
  'cnblogs.com': 'reference',
  'juejin.cn': 'reference',
  'segmentfault.com': 'reference',
  'oschina.net': 'reference',
  'teratail.com': 'reference',
  'note.com': 'reference',
  'hatena.ne.jp': 'reference',
  'developer.aliyun.com': 'reference',
  'cloud.tencent.com': 'reference',
  'infoq.cn': 'reference',
  'sspai.com': 'reference',
  'weread.qq.com': 'reference',
  'weread.com': 'reference',
  'zhihu.com': 'reference',
  'deepl.com': 'reference',
  'lingq.com': 'reference',
  'tutorialsdojo.com': 'reference',
  'eikaiwa.dmm.com': 'reference',
  'dmm.com': 'reference',
  'aws.training': 'reference',
  'skillbuilder.aws': 'reference',
  'learn.microsoft.com': 'reference',
  'developer.microsoft.com': 'reference',
  'quora.com': 'reference',
  'goodreads.com': 'reference',
  'libgen': 'reference',
  'scholar.google.com': 'reference',
  'arxiv.org': 'reference',
  'researchgate.net': 'reference',
  'academia.edu': 'reference',
  'mdn.': 'reference',

  // ── NSFW ──
  'pornhub.com': 'nsfw',
  'xvideos.com': 'nsfw',
  'xnxx.com': 'nsfw',
  'xhamster.com': 'nsfw',
  'redtube.com': 'nsfw',
  'brazzers.com': 'nsfw',
  'onlyfans.com': 'nsfw',
  'chaturbate.com': 'nsfw',
  'stripchat.com': 'nsfw',
  'nhentai.net': 'nsfw',
  'gelbooru.com': 'nsfw',
  'danbooru.donmai.us': 'nsfw',
  'rule34.xxx': 'nsfw',
  'e-hentai.org': 'nsfw',
  'exhentai.org': 'nsfw',
});

// How often the service worker checks for stale tabs (in minutes)
export const CHECK_INTERVAL_MINUTES = 30;

// How often to persist foreground-session dwell time while a tab is active
export const SESSION_CHECKPOINT_INTERVAL_MINUTES = 1;

// How often to sync with the native companion app (in minutes)
export const COMPANION_SYNC_INTERVAL_MINUTES = 60;

// Storage keys
export const STORAGE_KEYS = {
  TAB_REGISTRY: 'tabRegistry',         // Legacy registry object, migrated to per-tab keys
  TAB_REGISTRY_INDEX: 'tabRegistryIndex', // [tabId]
  TAB_ENTRY_PREFIX: 'tabEntry:',       // tabEntry:<tabId> -> { url, title, lastVisited, ... }
  CLOSED_LOG: 'closedLog',             // [{ url, title, category, closedAt, reason }]
  IDLE_PREDICTIONS: 'idlePredictions', // { [dayOfWeek]: { startHour, endHour, confidence } }
  USER_SETTINGS: 'userSettings',       // { enabled, customThresholds, ... }
  ACTIVE_SESSION: 'activeSession',      // { tabId, windowId, startedAt, url }
  RETURN_NOTIFICATION: 'returnNotification', // { pending: bool, closedTabs: [...] }
  COMPANION_STATUS: 'companionStatus', // { connected, lastSync, modelVersion }
  TAGGED_TABS: 'taggedTabs',           // { [tabId]: { reason, taggedAt, category } }
};

// Native messaging host name (must match the one registered in the companion app)
export const NATIVE_HOST_NAME = 'com.neuraljanitor.companion';
